# Every value the pipelines and profiles.yml need, under the names they read
# them by. Nothing here is secret - hostnames, item names and GUIDs only.
#
#   terraform output -raw gh_commands
#   terraform output -raw dev_env_file

locals {
  # Repository-level GitHub Actions variables. try() keeps this null-safe when
  # the ci environment is removed from var.environments.
  repo_variables = {
    DBT_FABRIC_HOST_CI            = try(fabric_warehouse.this["ci"].properties.connection_string, null)
    DBT_FABRIC_DATABASE_CI        = try(fabric_warehouse.this["ci"].display_name, null)
    DBT_FABRIC_SOURCE_DATABASE_CI = try(fabric_lakehouse.source["ci"].display_name, null)
  }

  # Environment-scoped variables, one block per deploy target.
  environment_variables = {
    for key, env in local.environments : key => {
      DBT_FABRIC_HOST            = fabric_warehouse.this[key].properties.connection_string
      DBT_FABRIC_DATABASE        = fabric_warehouse.this[key].display_name
      DBT_FABRIC_SOURCE_DATABASE = fabric_lakehouse.source[key].display_name
      DBT_FABRIC_WORKSPACE       = fabric_workspace.this[key].id
      DBT_FABRIC_DATALAKE_ID     = fabric_lakehouse.code[key].id
    } if env.deploy_target
  }
}

output "ci_variables" {
  description = "Per-environment connection values. DBT_FABRIC_DATALAKE_ID is null for environments that are not deploy targets."

  value = {
    for key, env in local.environments : key => {
      DBT_FABRIC_HOST            = fabric_warehouse.this[key].properties.connection_string
      DBT_FABRIC_DATABASE        = fabric_warehouse.this[key].display_name
      DBT_FABRIC_SOURCE_DATABASE = fabric_lakehouse.source[key].display_name
      DBT_FABRIC_WORKSPACE       = fabric_workspace.this[key].id
      DBT_FABRIC_DATALAKE_ID     = try(fabric_lakehouse.code[key].id, null)
      workspace_name             = fabric_workspace.this[key].display_name
    }
  }
}

output "github_repository_variables" {
  description = "Settings > Secrets and variables > Actions > Variables (repository level)."
  value       = local.repo_variables
}

output "github_environment_variables" {
  description = "Settings > Environments > <name> > Variables, one block per deploy target."
  value       = local.environment_variables
}

output "gh_commands" {
  description = "Paste-ready GitHub CLI commands. Run from the repo, after `gh auth login`."

  value = join("\n", concat(
    [
      "# ---------------------------------------------------------------------",
      "# Repository variables - Settings > Secrets and variables > Actions",
      "# ---------------------------------------------------------------------",
    ],
    [
      for name, value in local.repo_variables :
      format("gh variable set %s --body %q", name, value) if value != null
    ],
    [
      "",
      "# ---------------------------------------------------------------------",
      "# Environments - Settings > Environments. These must exist before the",
      "# `gh variable set --env` lines below will resolve.",
      "# ---------------------------------------------------------------------",
    ],
    [
      for env_name in sort(keys(local.environment_variables)) :
      format("gh api -X PUT repos/:owner/:repo/environments/%s --silent", env_name)
    ],
    [
      "",
      "# ---------------------------------------------------------------------",
      "# Environment variables - Settings > Environments",
      "# ---------------------------------------------------------------------",
    ],
    flatten([
      for env_name, vars in local.environment_variables : [
        for name, value in vars :
        format("gh variable set %s --env %s --body %q", name, env_name, value)
      ]
    ]),
    [
      "",
      "# ---------------------------------------------------------------------",
      "# Secrets - the service principal from docs/CLIENT_SETUP.md step 1.",
      "# Kept out of Terraform so the client secret never reaches the state file.",
      "# ---------------------------------------------------------------------",
      "gh secret set DBT_SP_TENANT_ID   --body \"<tenant id>\"",
      "gh secret set DBT_SP_CLIENT_ID   --body \"<application (client) id>\"",
      "gh secret set DBT_SP_CLIENT_SECRET --body \"<client secret>\"",
    ],
  ))
}

output "dev_env_file" {
  description = "Block for the developer's local .env (gitignored). Matches dbt/profiles.yml's variable names."

  value = join("\n", concat(
    [
      "# Local development - generated by infra/, see docs/ONBOARDING.md.",
      format("export DBT_FABRIC_HOST_DEV=%q", try(fabric_warehouse.this["dev"].properties.connection_string, "")),
      format("export DBT_FABRIC_DATABASE_DEV=%q", try(fabric_warehouse.this["dev"].display_name, "")),
      "",
      "# Same lakehouse name in every workspace, so one value covers all targets.",
      format("export DBT_FABRIC_SOURCE_DATABASE=%q", var.source_lakehouse_name),
      "",
      "# Only needed to run --target ci locally (service principal auth).",
      format("export DBT_FABRIC_HOST_CI=%q", try(fabric_warehouse.this["ci"].properties.connection_string, "")),
      format("export DBT_FABRIC_DATABASE_CI=%q", try(fabric_warehouse.this["ci"].display_name, "")),
      format("export DBT_FABRIC_SOURCE_DATABASE_CI=%q", var.source_lakehouse_name),
    ],
    [
      for key, vars in local.environment_variables :
      format("export DBT_FABRIC_HOST_%s=%q\nexport DBT_FABRIC_DATABASE_%s=%q", upper(key), vars.DBT_FABRIC_HOST, upper(key), vars.DBT_FABRIC_DATABASE)
    ],
  ))
}

output "workspace_ids" {
  description = "Workspace GUIDs, keyed by environment."
  value       = { for key in keys(local.environments) : key => fabric_workspace.this[key].id }
}

output "warehouse_host" {
  description = "Warehouse SQL endpoints, keyed by environment (DBT_FABRIC_HOST)."
  value       = { for key in keys(local.environments) : key => fabric_warehouse.this[key].properties.connection_string }
}

output "warehouse_name" {
  description = "Warehouse names, keyed by environment (DBT_FABRIC_DATABASE)."
  value       = { for key in keys(local.environments) : key => fabric_warehouse.this[key].display_name }
}

output "lakehouse_sql_endpoints" {
  description = "Source lakehouse SQL endpoints, keyed by environment. Check these when a first dbt run fails - provisioning is the usual cause."
  value = {
    for key in keys(local.environments) : key => {
      id                  = fabric_lakehouse.source[key].id
      provisioning_status = fabric_lakehouse.source[key].properties.sql_endpoint_properties.provisioning_status
    }
  }
}
